import { describe, it, expect } from 'vitest';
import type { Card } from './cards';
import { cardValue } from './cards';
import type { PlayerIndex } from './game';
import type { SubroutineDefinition } from './subroutine-types';
import { playCombat } from './combat';
import { createRng } from './rng';
import { createDeck, shuffle } from './deck';
import { deal, discardToCrib, discardLowestTwo, cut, hisHeels, type DiscardStrategy } from './deal';
import { playPegging, playLowestLegal, type PlayStrategy } from './pegging';
import { countHandEvents, countCribEvents } from './scoring';
import { pegSkillStrategy, discardSkillStrategy } from './ai';

function alwaysBurst(id: string, amount: number): SubroutineDefinition {
  return {
    id,
    name: id,
    archetype: 'exploit',
    trigger: { kind: 'always' },
    payload: { kind: 'directBurst', amount },
    tags: [],
  };
}

describe('playCombat', () => {
  it('resolves in the player\'s favor when only the player has a firing subroutine', () => {
    const result = playCombat([[alwaysBurst('a', 20)], []], { seed: 1, gaugeThreshold: 5 });
    expect(result.winner).toBe(0);
    expect(result.hands.length).toBeGreaterThan(0);
    expect(result.log.length).toBeGreaterThan(0);
    expect(result.log.every((e) => e.side === 0)).toBe(true);
  });

  it('resolves in the enemy\'s favor when only the enemy has a firing subroutine', () => {
    const result = playCombat([[], [alwaysBurst('b', 20)]], { seed: 1, gaugeThreshold: 5 });
    expect(result.winner).toBe(1);
    expect(result.log.every((e) => e.side === 1)).toBe(true);
  });

  it('is fully deterministic for the same seed', () => {
    const loadouts: [SubroutineDefinition[], SubroutineDefinition[]] = [
      [alwaysBurst('a', 3)],
      [alwaysBurst('b', 2)],
    ];
    const a = playCombat(loadouts, { seed: 42, gaugeThreshold: 8 });
    const b = playCombat(loadouts, { seed: 42, gaugeThreshold: 8 });
    expect(a).toEqual(b);
  });

  it('a symmetric duel between two firing loadouts resolves without throwing', () => {
    const loadouts: [SubroutineDefinition[], SubroutineDefinition[]] = [
      [alwaysBurst('a', 3)],
      [alwaysBurst('b', 3)],
    ];
    const result = playCombat(loadouts, { seed: 7, gaugeThreshold: 6 });
    expect([0, 1]).toContain(result.winner);
  });

  it('plays different hands for a different seed', () => {
    const loadouts: [SubroutineDefinition[], SubroutineDefinition[]] = [
      [alwaysBurst('a', 3)],
      [alwaysBurst('b', 3)],
    ];
    const a = playCombat(loadouts, { seed: 1, gaugeThreshold: 6 });
    const b = playCombat(loadouts, { seed: 2, gaugeThreshold: 6 });
    expect(a.hands).not.toEqual(b.hands);
  });

  it('throws rather than looping forever when neither side can ever get a turn', () => {
    expect(() => playCombat([[], []], { seed: 1, gaugeThreshold: 5, maxHands: 3 })).toThrow();
  });

  it('surfaces the player side\'s in-combat Heat generated by riskRewardBurst payloads', () => {
    const riskyPlayer: SubroutineDefinition = {
      id: 'a',
      name: 'a',
      archetype: 'exploit',
      trigger: { kind: 'always' },
      payload: { kind: 'riskRewardBurst', amount: 20, heatCost: 4 },
      tags: [],
    };
    const result = playCombat([[riskyPlayer], []], { seed: 1, gaugeThreshold: 5 });
    expect(result.winner).toBe(0);
    expect(result.playerHeatGenerated).toBeGreaterThan(0);
    expect(result.playerHeatGenerated % 4).toBe(0);
  });

  it('reports zero player Heat generated when nothing costs Heat', () => {
    const result = playCombat([[alwaysBurst('a', 20)], []], { seed: 1, gaugeThreshold: 5 });
    expect(result.playerHeatGenerated).toBe(0);
  });

  it('cribbageLayerManipulation markSuit credits a suitTally Accumulator through the full pipeline', () => {
    const suitMarker: SubroutineDefinition = {
      id: 'suit-marker',
      name: 'suit-marker',
      archetype: 'root',
      trigger: { kind: 'always' },
      payload: { kind: 'cribbageLayerManipulation', action: 'markSuit', suit: 0 },
      tags: [],
    };
    const suitPayoff: SubroutineDefinition = {
      id: 'suit-payoff',
      name: 'suit-payoff',
      archetype: 'malware',
      trigger: { kind: 'accumulator', metric: 'suitTally', suit: 0, threshold: 1 },
      payload: { kind: 'directBurst', amount: 60 },
      tags: [],
      reactive: true,
    };
    // suit-marker fires on a normal turn, registering a pending markSuit
    // -- consumed at the start of the *next* hand, immediately arming
    // and firing the Reactive suit-payoff via the credit alone, with no
    // card of that suit needing to actually be played.
    const result = playCombat([[suitMarker, suitPayoff], []], { seed: 1, gaugeThreshold: 5 });
    expect(result.winner).toBe(0);
    expect(result.log.some((e) => e.subroutineId === 'suit-payoff')).toBe(true);
  });

  it('cribbageLayerManipulation forceDiscard resolves through a full match without throwing', () => {
    const discardForcer: SubroutineDefinition = {
      id: 'discard-forcer',
      name: 'discard-forcer',
      archetype: 'root',
      trigger: { kind: 'always' },
      payload: { kind: 'cribbageLayerManipulation', action: 'forceDiscard' },
      tags: [],
    };
    expect(() => playCombat([[discardForcer, alwaysBurst('finisher', 20)], []], { seed: 3, gaugeThreshold: 5 })).not.toThrow();
  });

  it('a suitTally Accumulator fires from cards played, not from scoring', () => {
    const suitWatcher: SubroutineDefinition = {
      id: 'suit-watcher',
      name: 'suit-watcher',
      archetype: 'malware',
      trigger: { kind: 'accumulator', metric: 'suitTally', suit: 0, threshold: 2 },
      payload: { kind: 'directBurst', amount: 30 },
      tags: [],
      reactive: true,
    };
    // gaugeThreshold is deliberately unreachable within the hands this
    // takes to resolve, and side 1 is empty -- the only way
    // breachContainment can move is the suit-watcher actually firing
    // from real cards played during pegging.
    const result = playCombat([[suitWatcher], []], { seed: 1, gaugeThreshold: 100_000 });
    expect(result.winner).toBe(0);
    expect(result.log.length).toBeGreaterThan(0);
    expect(result.log.every((e) => e.side === 0 && e.subroutineId === 'suit-watcher')).toBe(true);
  });

  it('a global-pulse DoT ticks from combined scoring, independent of whose turn it is', () => {
    const globalDot: SubroutineDefinition = {
      id: 'global-dot',
      name: 'global-dot',
      archetype: 'malware',
      trigger: { kind: 'always' },
      payload: { kind: 'dot', amountPerTick: 30, cadence: 'globalPulse', duration: 5, pointsPerTick: 5 },
      tags: [],
    };
    // A low gaugeThreshold gets the dot registered on side 0's first
    // turn; after that, side 1 has an empty loadout (can never push
    // back), so any further movement toward side 0's win can only come
    // from global-pulse ticking off combined scoring, not from turns.
    const result = playCombat([[globalDot], []], { seed: 1, gaugeThreshold: 3 });
    expect(result.winner).toBe(0);
    expect(result.log.length).toBeGreaterThan(0);
  });

  it('a scheduledSabotage payload resolves at a later deal, driving the match to resolution', () => {
    const sabotageBurst: SubroutineDefinition = {
      id: 'sabotage-burst',
      name: 'sabotage-burst',
      archetype: 'root',
      trigger: { kind: 'always' },
      payload: { kind: 'scheduledSabotage', resolvesAt: 'nextDeal', effect: { kind: 'directBurst', amount: 20 } },
      tags: [],
    };
    // Side 1 has an empty loadout -- the only way breachContainment can
    // ever move is through side 0's scheduled sabotage actually
    // resolving on a later deal. If the resolution hook weren't wired
    // up, pending entries would pile up forever and this would run out
    // maxHands and throw instead of resolving.
    const result = playCombat([[sabotageBurst], []], { seed: 1, gaugeThreshold: 5 });
    expect(result.winner).toBe(0);
  });

  it('a Reactive piece fires mid-hand, bypassing the turn-gate entirely', () => {
    const reactiveFifteen: SubroutineDefinition = {
      id: 'reactive-fifteen',
      name: 'reactive-fifteen',
      archetype: 'exploit',
      trigger: { kind: 'occurrence', category: 'fifteen', variation: 'instant' },
      payload: { kind: 'directBurst', amount: 20 },
      tags: [],
      reactive: true,
    };
    // gaugeThreshold is deliberately unreachable within the hands this
    // takes to resolve -- side 0's own gauge should never cross via a
    // normal turn, so any side-0 fire in the log can only be the
    // Reactive path. Side 1 has an empty loadout, so it can never fire
    // even if it somehow got a turn.
    const result = playCombat([[reactiveFifteen], []], { seed: 1, gaugeThreshold: 100_000 });
    expect(result.winner).toBe(0);
    expect(result.log.length).toBeGreaterThan(0);
    expect(result.log.every((e) => e.side === 0 && e.subroutineId === 'reactive-fifteen')).toBe(true);
  });

  it(
    "the hand-lifecycle decomposition produces byte-for-byte identical HandResults to a direct game.ts replay for the same seed " +
      '(session 24 checkpoint B regression check)',
    () => {
      const result = playCombat([[alwaysBurst('winner', 1000)], []], { seed: 42, gaugeThreshold: 1 });
      expect(result.hands.length).toBeGreaterThan(0);

      // Independently replay the exact same rng sequence through game.ts's
      // granular pieces, in the same order combat.ts's decomposition calls
      // them, with the same default strategies -- if these two diverged, it
      // would mean the decomposition changed real game behavior.
      const rng = createRng(42);
      for (const hand of result.hands) {
        const shuffled = shuffle(createDeck(), rng);
        const { hands: dealtHands, stock } = deal(shuffled);
        const d0 = discardToCrib({ hand: dealtHands[0], isOwnCrib: hand.dealer === 0 }, discardLowestTwo);
        const d1 = discardToCrib({ hand: dealtHands[1], isOwnCrib: hand.dealer === 1 }, discardLowestTwo);
        const { starter } = cut(stock, rng);
        expect(starter).toEqual(hand.starter);
        expect(hisHeels(starter)).toBe(hand.hisHeelsPoints);

        const nonDealer = (1 - hand.dealer) as PlayerIndex;
        const kept: [Card[], Card[]] = [d0.keptHand, d1.keptHand];
        const { scores: peggingScores, events: peggingEvents } = playPegging(kept[0], kept[1], nonDealer, [playLowestLegal, playLowestLegal]);
        expect(peggingScores).toEqual(hand.peggingScores);
        expect(peggingEvents).toEqual(hand.peggingEvents);
        expect(countHandEvents(kept[nonDealer], starter)).toEqual(hand.nonDealerHandEvents);
        expect(countHandEvents(kept[hand.dealer], starter)).toEqual(hand.dealerHandEvents);
        expect(countCribEvents([...d0.discarded, ...d1.discarded], starter)).toEqual(hand.cribEvents);
      }
    },
  );

  it("recon's revealOpponentHand plumbs the real opponent hand through to the discard strategy's DiscardContext (session 24 checkpoint C end-to-end)", () => {
    const recon: SubroutineDefinition = {
      id: 'recon',
      name: 'recon',
      archetype: 'root',
      trigger: { kind: 'always' },
      payload: { kind: 'revealOpponentHand' },
      tags: [],
      firesAt: 'onDealt',
    };
    const seenKnownHands: (Card[] | undefined)[] = [];
    const spyDiscardStrategy: DiscardStrategy = (ctx) => {
      seenKnownHands.push(ctx.knownOpponentHand);
      const sorted = ctx.hand.slice().sort((a, b) => a.rank - b.rank);
      return [sorted[0], sorted[1]];
    };
    const result = playCombat([[recon, alwaysBurst('winner', 1000)], []], {
      seed: 5,
      gaugeThreshold: 1,
      discardStrategies: [spyDiscardStrategy, spyDiscardStrategy],
    });
    expect(result.hands.length).toBeGreaterThan(0);
    // Side 0 discards first each hand (combat.ts's fixed order) and has
    // the recon piece -- its DiscardContext should carry side 1's real,
    // full 6-card dealt hand. Side 1 has no recon piece of its own, so
    // its call sees nothing.
    expect(seenKnownHands[0]).toBeDefined();
    expect(seenKnownHands[0]).toHaveLength(6);
    expect(seenKnownHands[1]).toBeUndefined();
  });

  it("Root's forceDiscardCard manipulation bypasses the target's own discard strategy entirely (session 24 checkpoint D end-to-end)", () => {
    const manipulator: SubroutineDefinition = {
      id: 'manipulator',
      name: 'manipulator',
      archetype: 'root',
      trigger: { kind: 'always' },
      payload: { kind: 'forceDiscardCard' },
      tags: [],
      firesAt: 'onDealt',
    };
    let totalDiscardCalls = 0;
    const spyDiscardStrategy: DiscardStrategy = (ctx) => {
      totalDiscardCalls++;
      const sorted = ctx.hand.slice().sort((a, b) => a.rank - b.rank);
      return [sorted[0], sorted[1]];
    };
    const result = playCombat([[manipulator, alwaysBurst('winner', 1000)], []], {
      seed: 7,
      gaugeThreshold: 1,
      discardStrategies: [spyDiscardStrategy, spyDiscardStrategy],
    });
    expect(result.hands.length).toBeGreaterThan(0);
    // Shared discardStrategy is normally called once per side per hand
    // (2 calls/hand). Side 1 (the manipulation target) should never
    // actually reach it -- forcedDiscardPair overrides its call
    // entirely, so only side 0's own unmanipulated call goes through.
    expect(totalDiscardCalls).toBe(result.hands.length);
  });

  it('haste (ownGauge) banks initiative-gauge overflow that grants multiple turns on the next natural scoring event (session 24 checkpoint E end-to-end)', () => {
    const haste: SubroutineDefinition = {
      id: 'haste',
      name: 'haste',
      archetype: 'root',
      trigger: { kind: 'always' },
      payload: { kind: 'instantManipulation', target: 'ownGauge', amount: 15 },
      tags: [],
      firesAt: 'onDealt',
    };
    const burst = alwaysBurst('burst', 1);
    // gaugeThreshold=5, haste dumps 15 progress at deal-time -- already
    // 3 threshold-widths banked before any real Cribbage scoring even
    // happens. The very first positive-magnitude occurrence this hand
    // (His Heels, a peg play, or the show) should release all 3 banked
    // turns at once via gauges.ts's addPoints overflow-carrying, each
    // firing burst -- winThreshold=3 lets that single release resolve
    // the match immediately, well within hand 1.
    const result = playCombat([[haste, burst], []], { seed: 3, gaugeThreshold: 5, winThreshold: 3 });
    expect(result.winner).toBe(0);
    expect(result.log.filter((e) => e.subroutineId === 'burst').length).toBeGreaterThanOrEqual(3);
  });

  it("recon's revealCrib and revealOpponentKeptHand plumb real crib/kept-hand data through to the pegging strategy's PlayContext (session 24 checkpoint G end-to-end)", () => {
    const cribRecon: SubroutineDefinition = {
      id: 'crib-recon',
      name: 'crib-recon',
      archetype: 'root',
      trigger: { kind: 'always' },
      payload: { kind: 'revealCrib' },
      tags: [],
      firesAt: 'onCribSelected',
    };
    const handRecon: SubroutineDefinition = {
      id: 'hand-recon',
      name: 'hand-recon',
      archetype: 'root',
      trigger: { kind: 'always' },
      payload: { kind: 'revealOpponentKeptHand' },
      tags: [],
      firesAt: 'onPlayPhaseStart',
    };
    const burst = alwaysBurst('winner', 1000);
    let sawKnownCrib = false;
    let sawKnownOpponentHand = false;
    const spyPlayStrategy: PlayStrategy = (ctx) => {
      if (ctx.knownCrib) sawKnownCrib = true;
      if (ctx.knownOpponentHand) sawKnownOpponentHand = true;
      return ctx.legalCards.slice().sort((a, b) => cardValue(a) - cardValue(b))[0];
    };
    // Pegging always plays out in full before any occurrence (and so any
    // win) can be processed (combat.ts builds occurrencesForHand from
    // the already-complete HandResult) -- both flags should already be
    // set by the time this returns, regardless of exactly which hand
    // the match resolves in.
    const result = playCombat([[cribRecon, handRecon, burst], []], {
      seed: 11,
      gaugeThreshold: 1,
      playStrategies: [spyPlayStrategy, spyPlayStrategy],
    });
    expect(result.hands.length).toBeGreaterThan(0);
    expect(sawKnownCrib).toBe(true);
    expect(sawKnownOpponentHand).toBe(true);
  });

  it('pegSkillStrategy plugs into real combat via per-side playStrategies without throwing (session 24 tunable-skill AI checkpoint B smoke test)', () => {
    const burst = alwaysBurst('winner', 20);
    const result = playCombat([[burst], [burst]], {
      seed: 13,
      gaugeThreshold: 5,
      winThreshold: 30,
      playStrategies: [pegSkillStrategy(1), pegSkillStrategy(0)],
    });
    expect([0, 1]).toContain(result.winner);
  });

  it('discardSkillStrategy plugs into real combat via per-side discardStrategies without throwing (session 24 tunable-skill AI checkpoint C smoke test)', () => {
    const burst = alwaysBurst('winner', 20);
    const result = playCombat([[burst], [burst]], {
      seed: 17,
      gaugeThreshold: 5,
      winThreshold: 30,
      discardStrategies: [discardSkillStrategy(1), discardSkillStrategy(0)],
    });
    expect([0, 1]).toContain(result.winner);
  });

  describe('escalation', () => {
    // A tiny, always-firing burst against a winThreshold it could never
    // realistically reach through normal play within a sane hand count
    // -- only escalation's shrinking threshold (starts at hand 100,
    // floors at 10) brings the bar down to something this weak enough
    // to actually cross. Confirmed empirically to resolve consistently
    // at hand 261 for this exact setup.
    const weakBurst = (id: string): SubroutineDefinition => ({
      id,
      name: id,
      archetype: 'exploit',
      trigger: { kind: 'always' },
      payload: { kind: 'directBurst', amount: 0.01 },
      tags: [],
    });

    it('does not resolve before escalation starts (hand 100)', () => {
      expect(() => playCombat([[weakBurst('a')], []], { seed: 1, gaugeThreshold: 3, winThreshold: 15, maxHands: 90 })).toThrow(
        /did not resolve/,
      );
    });

    it('rescues a match that would otherwise never reach its own winThreshold, correctly attributing the win', () => {
      // Side 1 fires nothing at all -- if escalation ever incorrectly
      // resolved in side 1's favor (e.g. a floor/shrink bug), this would
      // catch it immediately.
      const result = playCombat([[weakBurst('a')], []], { seed: 1, gaugeThreshold: 3, winThreshold: 15, maxHands: 300 });
      expect(result.winner).toBe(0);
      expect(result.hands.length).toBeGreaterThan(100); // genuinely resolved via escalation, not a fluke early win
    });
  });
});
