import { describe, it, expect } from 'vitest';
import type { SubroutineDefinition } from './subroutine-types';
import { playCombat } from './combat';

function alwaysBurst(id: string, amount: number): SubroutineDefinition {
  return {
    id,
    name: id,
    archetype: 'exploit',
    trigger: { kind: 'always' },
    payload: { kind: 'directBurst', amount },
    tags: [],
  };
}

describe('playCombat', () => {
  it('resolves in the player\'s favor when only the player has a firing subroutine', () => {
    const result = playCombat([[alwaysBurst('a', 20)], []], { seed: 1, gaugeThreshold: 5 });
    expect(result.winner).toBe(0);
    expect(result.hands.length).toBeGreaterThan(0);
    expect(result.log.length).toBeGreaterThan(0);
    expect(result.log.every((e) => e.side === 0)).toBe(true);
  });

  it('resolves in the enemy\'s favor when only the enemy has a firing subroutine', () => {
    const result = playCombat([[], [alwaysBurst('b', 20)]], { seed: 1, gaugeThreshold: 5 });
    expect(result.winner).toBe(1);
    expect(result.log.every((e) => e.side === 1)).toBe(true);
  });

  it('is fully deterministic for the same seed', () => {
    const loadouts: [SubroutineDefinition[], SubroutineDefinition[]] = [
      [alwaysBurst('a', 3)],
      [alwaysBurst('b', 2)],
    ];
    const a = playCombat(loadouts, { seed: 42, gaugeThreshold: 8 });
    const b = playCombat(loadouts, { seed: 42, gaugeThreshold: 8 });
    expect(a).toEqual(b);
  });

  it('a symmetric duel between two firing loadouts resolves without throwing', () => {
    const loadouts: [SubroutineDefinition[], SubroutineDefinition[]] = [
      [alwaysBurst('a', 3)],
      [alwaysBurst('b', 3)],
    ];
    const result = playCombat(loadouts, { seed: 7, gaugeThreshold: 6 });
    expect([0, 1]).toContain(result.winner);
  });

  it('plays different hands for a different seed', () => {
    const loadouts: [SubroutineDefinition[], SubroutineDefinition[]] = [
      [alwaysBurst('a', 3)],
      [alwaysBurst('b', 3)],
    ];
    const a = playCombat(loadouts, { seed: 1, gaugeThreshold: 6 });
    const b = playCombat(loadouts, { seed: 2, gaugeThreshold: 6 });
    expect(a.hands).not.toEqual(b.hands);
  });

  it('throws rather than looping forever when neither side can ever get a turn', () => {
    expect(() => playCombat([[], []], { seed: 1, gaugeThreshold: 5, maxHands: 3 })).toThrow();
  });

  it('surfaces the player side\'s in-combat Heat generated by riskRewardBurst payloads', () => {
    const riskyPlayer: SubroutineDefinition = {
      id: 'a',
      name: 'a',
      archetype: 'exploit',
      trigger: { kind: 'always' },
      payload: { kind: 'riskRewardBurst', amount: 20, heatCost: 4 },
      tags: [],
    };
    const result = playCombat([[riskyPlayer], []], { seed: 1, gaugeThreshold: 5 });
    expect(result.winner).toBe(0);
    expect(result.playerHeatGenerated).toBeGreaterThan(0);
    expect(result.playerHeatGenerated % 4).toBe(0);
  });

  it('reports zero player Heat generated when nothing costs Heat', () => {
    const result = playCombat([[alwaysBurst('a', 20)], []], { seed: 1, gaugeThreshold: 5 });
    expect(result.playerHeatGenerated).toBe(0);
  });

  it('a global-pulse DoT ticks from combined scoring, independent of whose turn it is', () => {
    const globalDot: SubroutineDefinition = {
      id: 'global-dot',
      name: 'global-dot',
      archetype: 'malware',
      trigger: { kind: 'always' },
      payload: { kind: 'dot', amountPerTick: 30, cadence: 'globalPulse', duration: 5, pointsPerTick: 5 },
      tags: [],
    };
    // A low gaugeThreshold gets the dot registered on side 0's first
    // turn; after that, side 1 has an empty loadout (can never push
    // back), so any further movement toward side 0's win can only come
    // from global-pulse ticking off combined scoring, not from turns.
    const result = playCombat([[globalDot], []], { seed: 1, gaugeThreshold: 3 });
    expect(result.winner).toBe(0);
    expect(result.log.length).toBeGreaterThan(0);
  });

  it('a Reactive piece fires mid-hand, bypassing the turn-gate entirely', () => {
    const reactiveFifteen: SubroutineDefinition = {
      id: 'reactive-fifteen',
      name: 'reactive-fifteen',
      archetype: 'exploit',
      trigger: { kind: 'occurrence', category: 'fifteen', variation: 'instant' },
      payload: { kind: 'directBurst', amount: 20 },
      tags: [],
      reactive: true,
    };
    // gaugeThreshold is deliberately unreachable within the hands this
    // takes to resolve -- side 0's own gauge should never cross via a
    // normal turn, so any side-0 fire in the log can only be the
    // Reactive path. Side 1 has an empty loadout, so it can never fire
    // even if it somehow got a turn.
    const result = playCombat([[reactiveFifteen], []], { seed: 1, gaugeThreshold: 100_000 });
    expect(result.winner).toBe(0);
    expect(result.log.length).toBeGreaterThan(0);
    expect(result.log.every((e) => e.side === 0 && e.subroutineId === 'reactive-fifteen')).toBe(true);
  });
});
